### YamlMime:Lifecycle
metadata:
  title: Virtualizare aplicație Microsoft 5.0
  description: Microsoft Application Virtualization 5.0 urmează Politica privind ciclul de viață fix.
  ms.date: 07/28/2020
  ms.openlocfilehash: 537410789f17e2ca2d9308c1814f22f823288b32
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: ro-RO
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "860944"
name: Virtualizare aplicație Microsoft 5.0
summary: >+
  Microsoft Application Virtualization 5.0 urmează Politica privind ciclul de viață [fix.](/lifecycle/policies/fixed)


  Acest lucru este valabil pentru următoarele ediții: pentru Servicii desktop la distanță, pentru Servicii terminale, pentru desktopuri Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 01/10/2023
releases:
- version: Service Pack 3
  startDate: 12/08/2014
  endDate: 01/10/2023
- version: Service Pack 2
  startDate: 12/02/2013
  endDate: 01/12/2016
- version: Service Pack 1
  startDate: 04/10/2013
  endDate: 01/13/2015
- version: Original Release
  startDate: 11/01/2012
  endDate: 07/08/2014
content: "\n## <a name=\"links\"></a>Legături \n* [Informații despre produs](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n* [Politica pachetului service pack](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Edițiile \n* pentru servicii desktop la distanță\n* pentru Servicii terminale\n* pentru desktopuri Windows"
