### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 urmează Politica fixă privind ciclul de viață.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 urmează Politica [fixă](/lifecycle/policies/fixed) privind ciclul de viață.


  > [!IMPORTANT]
  > Suportul pentru acest produs s-a încheiat. A se vedea orientările privind migrarea de mai jos.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Linkuri 
  * [Instrucțiuni pentru migrare](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Instrucțiuni suplimentare privind migrarea](/mem/configmgr/core/migration/planning-for-migration)