### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.0 pentru desktop-uri Windows
  description: Microsoft Application Virtualization Hosting 5.0 pentru Desktop-uri Windows urmează Politica privind ciclul de viață fix.
  ms.date: 07/28/2020
  ms.openlocfilehash: dff04b865491bfb99aa8d20e556aafd434a59398
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: ro-RO
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "860935"
name: Microsoft Application Virtualization Hosting 5.0 pentru desktop-uri Windows
summary: >+
  Microsoft Application Virtualization Hosting 5.0 pentru Desktop-uri Windows urmează Politica privind ciclul de viață [fix.](/lifecycle/policies/fixed)


  Acest lucru este valabil pentru următoarele ediții: pentru Desktop-uri Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Service Pack 3
  startDate: 12/08/2014
  endDate: 04/14/2026
- version: Service Pack 2
  startDate: 11/08/2013
  endDate: 01/12/2016
- version: Service Pack 1
  startDate: 04/10/2013
  endDate: 01/13/2015
- version: Original Release
  startDate: 11/01/2012
  endDate: 07/08/2014
content: "\n## <a name=\"links\"></a>Legături \n* [Informații despre produs](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Politica pachetului service pack](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Edițiile \n* pentru desktopuri Windows"
