### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Microsoft System Center Configuration Manager 2007 R2 urmează Politica fixă privind ciclul de viață.
  ms.date: 07/28/2020
  ms.openlocfilehash: 0da71b9a2886e1a7012339ebef9a5fbe64f8811e
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: ro-RO
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "834590"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  Microsoft System Center Configuration Manager 2007 R2 urmează Politica [fixă](/lifecycle/policies/fixed) privind ciclul de viață.



  > [!IMPORTANT]

  > Suportul pentru acest produs s-a încheiat. A se vedea orientările privind migrarea de mai jos.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Linkuri \n* [Instrucțiuni pentru migrare](/mem/configmgr/core/migration/planning-for-migration)\n* [Instrucțiuni suplimentare privind migrarea](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
