### YamlMime:Lifecycle
metadata:
  title: Securitatea clientului Microsoft Forefront
  description: Microsoft Forefront Client Security urmează politica de ciclu de viață fixă.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: ro-RO
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908870"
name: Securitatea clientului Microsoft Forefront
summary: >+
  Microsoft Forefront Client Security urmează politica de ciclu de viață [fixă](/lifecycle/policies/fixed) .


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Linkuri \n* [Protecție Endpoint centru de sistem](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront Client Security a fost întrerupt. Asistența se încheie pe 14 iulie, 2015. Actualizările de definiție antimalware și antispyware nu vor mai fi disponibile după sfârșitul suportului pentru versiunea de produs. Vă rugăm să evaluați protecția Endpoint System Center ca înlocuitor."
