### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: Microsoft Application Virtualization 5.1 urmează Politica fixă privind ciclul de viață.
  ms.date: 09/10/2020
  keywords: for Remote Desktop Services,for Windows Desktops
  ms.openlocfilehash: b6ca3da5136031bbb6e140f3fa5124ef7b2e4ed6
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: ro-RO
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1001957"
name: Microsoft Application Virtualization 5.1
summary: >+
  Microsoft Application Virtualization 5.1 urmează Politica [fixă](/lifecycle/policies/fixed) privind ciclul de viață.


  Acest lucru este valabil pentru următoarele ediții: pentru Remote Desktop Services, pentru Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Linkuri \n* [Informații despre produs](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Ediții \n* for Remote Desktop Services\n* for Windows Desktops"
