### YamlMime:Lifecycle
metadata:
  title: Virtualizare aplicație Microsoft 4.5
  description: Microsoft Application Virtualization 4.5 urmează Politica privind ciclul de viață fix.
  ms.date: 07/28/2020
  ms.openlocfilehash: 9280ac5223f15be20ed2c04fe29b25fd57417b6a
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: ro-RO
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "834716"
name: Virtualizare aplicație Microsoft 4.5
summary: >
  Microsoft Application Virtualization 4.5 urmează Politica privind ciclul de viață [fix.](/lifecycle/policies/fixed)


  Acest lucru este valabil pentru următoarele ediții: pentru Terminal Services, pentru Desktop-uri Windows


  > [!IMPORTANT]

  > Suportul pentru acest produs s-a încheiat. A se vedea orientările privind migrația de mai jos.
products:
- windows
policyType: fixed
supportDates:
  start: 11/23/2008
  end: 01/14/2014
  extendedEnd: 01/08/2019
releases:
- version: Service Pack 2
  startDate: 08/15/2010
  endDate: 01/08/2019
- version: Service Pack 1
  startDate: 12/13/2009
  endDate: 10/11/2011
- version: Original Release
  startDate: 11/23/2008
  endDate: 01/11/2011
content: "\n## <a name=\"links\"></a>Legături \n* [Orientări privind migrația](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Politica pachetului service pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Deoarece clientul App-V 4.6 utilizează serverul App-V 4.5, serverul App-V 4.5 va continua să fie acceptat în conformitate cu datele ciclului de viață al Aplicației-V 4.6 atunci când este utilizat cu clientul App-V 4.6 acceptat.\n\n## <a name=\"editions\"></a>Edițiile \n* pentru Servicii terminale\n* pentru desktopuri Windows"
