### YamlMime:Lifecycle
metadata:
  title: Securitatea clientului Microsoft Forefront
  description: Microsoft Forefront Client Security urmează politica de ciclu de viață fixă.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: ro-RO
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924268"
name: Securitatea clientului Microsoft Forefront
summary: >+
  Microsoft Forefront Client Security urmează politica de ciclu de viață [fixă](/lifecycle/policies/fixed) .


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Linkuri \n* [Protecție Endpoint centru de sistem](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security a fost întrerupt din 14 iulie 2015. Actualizările de definiție antimalware și antispyware nu vor mai fi disponibile după sfârșitul suportului pentru versiunea de produs. Vă rugăm să evaluați protecția Endpoint System Center ca înlocuitor."
