### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.5
  description: Microsoft Application Virtualization 4.5 urmează Politica fixă privind ciclul de viață.
  ms.date: 09/01/2020
  keywords: for Terminal Services,for Windows Desktops
  ms.openlocfilehash: d70bed6b9c9e05d19efb27509f15e13fb8bf5735
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: ro-RO
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4108315"
name: Microsoft Application Virtualization 4.5
summary: >
  Microsoft Application Virtualization 4.5 urmează Politica [fixă](/lifecycle/policies/fixed) privind ciclul de viață.


  Acesta se aplică următoarelor ediții: for Terminal Services, for Windows Desktops


  > [!IMPORTANT]

  > Suportul pentru acest produs s-a încheiat. A se vedea orientările privind migrarea de mai jos.
products:
- windows
policyType: fixed
supportDates:
  start: 2008-11-23T00:00:00.000-08:00
  end: 2014-01-14T22:59:59.999-08:00
  extendedEnd: 2019-01-08T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2010-08-15T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2009-12-13T00:00:00.000-08:00
  endDate: 2011-10-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2008-11-23T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Linkuri \n* [Instrucțiuni pentru migrare](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Politica Service Pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Deoarece clientul App-V 4.6 utilizează serverul App-V 4.5, serverul App-V 4.5 va continua să beneficieze de asistență în conformitate cu datele ciclului de viață al App-V 4.6 atunci când este utilizat cu clientul App-V 4.6 acceptat.\n\n## <a name=\"editions\"></a>Ediții \n* for Terminal Services\n* for Windows Desktops"
