### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization urmează Politica fixă privind ciclul de viață.
  ms.date: 09/10/2020
  keywords: 4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1
  ms.openlocfilehash: 6b63a556c63bca08045d0335bd9233a0ae07a878
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: ro-RO
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4119859"
name: SoftGrid Application Virtualization
summary: >
  SoftGrid Application Virtualization urmează Politica [fixă](/lifecycle/policies/fixed) privind ciclul de viață.


  Aceasta se aplică edițiilor următoare: 4.1 for Desktops, 4.2 for Desktops, for Terminal Services 4.1


  > [!IMPORTANT]

  > Suportul s-a încheiat. A se vedea orientările privind migrarea de mai jos.
products:
- windows
policyType: fixed
supportDates:
  start: 2007-05-25T00:00:00.000-08:00
  end: 2012-07-10T22:59:59.999-08:00
  extendedEnd: 2017-07-11T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-05-25T00:00:00.000-08:00
  endDate: 2017-07-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Linkuri \n* [Instrucțiuni pentru migrare](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Ediții \n* 4.1 for Desktops\n* 4.2 for Desktops\n* for Terminal Services 4.1"
